# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#                                       1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

sum_of_num = 0
first_num = 1
second_num = 2
temp_num = 0
max_num = 4000000

while second_num < max_num:
    if(second_num % 2 == 0):
        sum_of_num += second_num
    
    temp_num = second_num
    second_num += first_num
    first_num = temp_num

print(sum_of_num)